### ISSUE TITLE
Repeated declaration of ds18b20crc (3 times!)

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#15]
Hey,

I know that #12 is still open, but this definitely needs a separate issue. The `ds18b20crc` function is declared in three places.

Here:
https://github.com/mazaczysko/ds18b20-logger/blob/6bb4c33412ffe4669f5b0e2aeffeb479b1bddd0f/master/sort.c#L36

Heeere:
https://github.com/mazaczysko/ds18b20-logger/blob/6bb4c33412ffe4669f5b0e2aeffeb479b1bddd0f/master/masterfunc.c#L20

Aaaand heere:
https://github.com/mazaczysko/ds18b20-logger/blob/6bb4c33412ffe4669f5b0e2aeffeb479b1bddd0f/master/debin.c#L48

With `static` keyword each time...
<img width=200px src=https://user-images.githubusercontent.com/6173262/50377391-ca09c680-061c-11e9-96dc-282f23c4ec8f.png></img>

**Comment by mazaczysko** [comment]
Of course it isn't necessary, thanks for reporting.
