### ISSUE TITLE
Obfuscated arguments system

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#20]
Why are you using bitwise operations for parsing command line arguments? It makes whole thing harder to read and less flexible.
Why not use a dedicated `struct` (with bit fields, if you really want to save some memory)?

**Comment by mazaczysko** [comment]
I've read in my book that portability problems could occur when using bit fields. That's why I will probably use ```argp``` library.

**Comment by Jacajack** [comment]
No, you didn't. I said all that on the phone.

Bit fields alone are not a problem that serious. You wanted to put them in a union with an unsigned character to check if any flag is set. This, however, is an overkill and is a bad and idiotic idea.

**Comment by mazaczysko** [comment]
It wasn't unsigned character, but anyway you convinced me that it is not the way I really want to do my arguments system on.

**Comment by Jacajack** [comment]
Now, my dear, look up the definition of `uint8_t`
