### ISSUE TITLE
Your file format (or code) is not portable

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#25]
Hey, I noticed that your program behaves differently on PowerPC architecture.

amd64:
```
$ echo "5b01020304202020202020202020202020feff5d05" | xxd -r -p > tricky.bin
$ ./masterbin -d tricky.bin
./masterbin: FLAG_DEBIN is active! Other flags will be skipped!
[ 2314885530346783233 0x2020202020202020 -2 ]

```

PowerPC:
```
$ echo "5b01020304202020202020202020202020feff5d05" | xxd -r -p > tricky.bin
$ ./masterbin -d tricky.bin
./masterbin: FLAG_DEBIN is active! Other flags will be skipped!
[72623860245078084 0x2020202020202020 -257]
```

Not to mention some compilations warnings - mostly `printf()` format issues

**Comment by mazaczysko** [comment]
Hey, I've changed some code in  [ 4573c31](https://github.com/mazaczysko/ds18b20-logger/commit/4573c3100ac7c50bb4915f1df08d6e06b4da8b70). Please try the newest version of ds18b20-logger and let me know if the problem still occurs.

**Comment by Jacajack** [comment]
Can't check right now, but looking at the changes, I assure you it still does.
