### ISSUE TITLE
Large files are still not handled properly

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#35]
Despite adding proper compilation flags, your program still doesn't handle large files well:
```
$ awk 'BEGIN{for(i=0;i<255652816;i++)printf("5b2020202020202020202020202020202020205ded");}' | xxd -r -p > bazinga.bin
$ ./masterbin -d bazinga.bin 
./masterbin: 'ftell' error!
```

Compile with `-m32`.

**Comment by mazaczysko** [comment]
This changes should do the job [a107844](https://github.com/mazaczysko/ds18b20-logger/commit/a107844a4857a7a9cf29c31b869468693a1db22d).

**Comment by Jacajack** [comment]
This problem is not solved yet. It's just different and you haven't ran tests as usual...
So, `bazinga.bin` contains 255652816 frames, right? Let's see:
```
./masterbin -d bazinga.bin > bazinga_out.txt
./masterbin: file contains corrupted data! Use '--fix' flag to remove damaged data.
```
That's suspicious... Now, if you try `wc -l bazinga_out.txt` you get 51130564. You somehow lost 204522252 frames!
