### ISSUE TITLE
Weird command line arguments behavior

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#39]
That's understandable:
```
$ ./masterbin
./masterbin: mode not specified!
```

This as well:
```
$ ./masterbin -c
./masterbin: tty not specified!
```

But why am I prompted to specify TTY if I just want my data in Gnuplot's format?
```
$ ./masterbin -g
./masterbin: tty not specified!
```

**Comment by mazaczysko** [comment]
Of course you shouldn't be prompted like that.
Now it will be handled.
https://github.com/mazaczysko/ds18b20-logger/blob/ae654af7cb70618bb1c3faf071ff1d8ec48d15a3/master/args.c#L210-L214
