### ISSUE TITLE
The formatting of incoming data is not checked

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#40]
You're parsing received data with `scanf`. That's great, but you're not checking if `scanf` actually read something. If something goes wrong, you're going to log some garbage data!

https://github.com/mazaczysko/ds18b20-logger/blob/2f9594475d9976a68bc6321fc8af27a255877bf4/master/masterfunc.c#L117-L155

**Comment by mazaczysko** [comment]
This code should do the job [ae654af](https://github.com/mazaczysko/ds18b20-logger/commit/ae654af7cb70618bb1c3faf071ff1d8ec48d15a3).
