### ISSUE TITLE
You're not handling fread errors properly

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#41]
Your code:
https://github.com/mazaczysko/ds18b20-logger/blob/ae654af7cb70618bb1c3faf071ff1d8ec48d15a3/master/sort.c#L90-L96

`man 3 fread`:
>  On success, fread() and fwrite() return the number of items read or written.  This number equals the number of bytes transferred only when size is 1.
       If an error occurs, or the end of the file is reached, the return value is a short item count (or zero).
       
> fread() does not distinguish between end-of-file and error, and callers must use feof(3) and ferror(3) to determine which occurred.

Can you read the manual pages at least once?

**Comment by mazaczysko** [comment]
New code here [720cf00](https://github.com/mazaczysko/ds18b20-logger/commit/720cf0021e5254751910e7d6904bbd9cf468f453).

**Comment by Jacajack** [comment]
This does not solve the issue. _**Read the goddamn manpages...**_

**Comment by Jacajack** [comment]
I'll help you out a bit:
`man ferror`:
> ERRORS
>       These  functions  should  not  fail  and do not set the external variable errno.  (However, in case fileno() detects that its argument is not a valid
       stream, it must return -1 and set errno to EBADF.)
