### ISSUE TITLE
Segmentation fault - help needed

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/ds18b20-logger#9]
Hello Mister!

Your program causes segmentation fault on my machine! I can't _debinarize_ my precious and confidential temperature logs! Please fix as soon as possible!

<img width=600px src=https://user-images.githubusercontent.com/6173262/50374142-ef311180-05e9-11e9-9a2b-af8ea2ed1d43.png></img>

Kindly, thank you!

**Comment by mazaczysko** [comment]
Hello!
I am so sorry because you had to wait but due to Christmas in my village electricity was turned off like every year.
Can you send me specification of your machine?
It should help to solve the problem quicker.

**Comment by Jacajack** [comment]
I am indeed very sorry to hear that, sir.
Here's specification of my machine:
![screenshot from 2018-12-29 01-28-41](https://user-images.githubusercontent.com/6173262/50531430-02703f80-0b0a-11e9-846e-7edeb2aa6250.png)

**Comment by mazaczysko** [comment]
Ohh sir...
Now I know the problem!
Unfortunately your machine have too few RAM to operate with that large files!
You can try to add more memory to SWAP, it should help.
Otherwise you can add more RAM to your machine, if you need money - try this [GoFundMe](https://www.gofundme.com/)

**Comment by Jacajack** [comment]
This is unfortunate. I'll have to sell my Lamborghini and mansion in order to buy more RAM. Meanwhile, please add message informing potential users about insufficient memory.

**Comment by mazaczysko** [comment]
I will.
Thank you.
